spring:
  application:
    name: pathFinder-spring-backend
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.H2Dialect # 전역 설정 (개별 설정으로 오버라이드 가능)

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.hibernate: INFO
    com.zaxxer.hikari: INFO
    com.coralstay: INFO

app:
  datasource:
    baseline:
      url: jdbc:h2:./build/db/baselinedb
      driver-class-name: org.h2.Driver
      username: sa
      password:
    field:
      url: jdbc:h2:./build/db/fielddb
      driver-class-name: org.h2.Driver
      username: sa
      password:
    insights:
      url: jdbc:h2:./build/db/insightsdb
      driver-class-name: org.h2.Driver
      username: sa
      password:
    progress:
      url: jdbc:h2:./build/db/progressdb
      driver-class-name: org.h2.Driver
      username: sa
      password:
    valuation:
      url: jdbc:h2:./build/db/valuationdb
      driver-class-name: org.h2.Driver
      username: sa
      password:
